server:
  port: 8008

spring:
  application:
    name: cloud-payment-hystrix

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/