server:
  port: 80

spring:
  application:
    name: cloud-hystrix-order

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/


feign:
  # 支持在客户端使用hystrix做服务降级
  hystrix:
    enabled: true
  # 设置openFeign的读取、连接超时时间
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000

# 设置客户端服务降级默认的超时时间 （客户端使用hystrix，一定要配上默认的超时时间，否则可能存在疯狂调兜底方法）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000